// <auto-generated />
using HelloApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20230125132353_AddPriority")]
    partial class AddPriority
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelloApi.Models.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsComplete = true,
                            Name = "Make a cup of tea",
                            Prority = 0
                        },
                        new
                        {
                            Id = 2L,
                            IsComplete = false,
                            Name = "Tidy your code",
                            Prority = 1
                        },
                        new
                        {
                            Id = 3L,
                            IsComplete = false,
                            Name = "Learn something new",
                            Prority = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
